spring.application.name=demo
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}


DB_URL=jdbc:mysql://railway.internal:3306/railway
DB_USER=root
DB_PASS=dqxxeWKExUbLivNqFYGEasIBEQjNxNen

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lakshmananvishnusfpro@gmail.com
spring.mail.password=sevo vteb krzd kmyg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true